import type { NextPage } from "next";
import { DefaultUser } from "next-auth";
import { signIn, signOut } from "next-auth/react";
import Head from "next/head";
import Image from "next/image";
import { trpc } from "../utils/trpc";

type AuthProviderProps = {
  name: string;
  logo: string;
  provider: string;
};
type UserDataProps = {
  user: DefaultUser;
};

const Home: NextPage = () => {
  // const hello = trpc.useQuery(["example.hello", { text: "from tRPC" }]);
  const session = trpc.useQuery(["auth.getSession"]);

  return (
    <>
      <Head>
        <title>Shortify - ln</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4">
        <h1 className="text-5xl md:text-[5rem] leading-normal font-extrabold text-gray-700">
          Shortify - <span className="text-purple-300">ln</span>
        </h1>

        <div className="grid gap-3 pt-3 mt-10 text-center md:grid-cols-2 lg:w-2/3">
          <AuthProvider
            name="Google"
            provider="google"
            logo="/images/google.svg"
          />
          <AuthProvider
            name="Facebook"
            provider="facebook"
            logo="/images/facebook.svg"
          />
          <AuthProvider
            name="Instagram"
            provider="instagram"
            logo="/images/instagram.svg"
          />
          <AuthProvider
            name="GitHub"
            provider="github"
            logo="/images/github.svg"
          />
        </div>

        { session.isLoading && <p>Loading...</p> }
        { session.isSuccess && <p>SUCCESS</p> }
        { session.isError && <p>{ session.error.message }</p> }
        { session.data && <UserData user={session.data.user}/> }

        <button onClick={() => signOut()}>SIGNOUT</button>
      </main>
    </>
  );
};

const AuthProvider = ({
  name,
  logo,
  provider,
}: AuthProviderProps) => {
  return (
    <button 
      onClick={() => signIn(provider)}
      className="flex flex-col items-center justify-center p-6 cursor-pointer duration-500 border-2 border-gray-500 rounded shadow-xl motion-safe:hover:scale-[1.025]"
    >
      <Image src={logo} alt={`${name} logo`} width="54" height="54" />
      <h2 className="mt-3 text-xl text-violet-500">
        Sign In with { name }
      </h2>
    </button>
  );
};

const UserData = ({user}: UserDataProps) => {
  return (
    <ul>
      { Object
        .entries(user)
        .map(({ 0: key, 1: val }) => (<li key={key}>{ `${key}: ${val}` }</li>)) }
    </ul>
  );
};




export default Home;
