import Head from "next/head";
import Navbar from "./Navbar";
import Toastr from "./Toastr";
import { PropsWithChildren } from "react";

const Layout: React.FC<PropsWithChildren> = ({children}) => {
  return (
    <>
      <Head>
        <title>Shortify - ln</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-1 flex-col items-center min-h-screen isolate bg-white dark:bg-[#181818]">
        <header className="w-full sticky top-0">
          <Navbar />
        </header>

        <div className="pt-[2rem] md:pt-[3rem] w-full pb-5 md:pb-8 flex-1">
          <div className="container mx-auto px-6 md:px-9 flex flex-1 justify-center order-first md:order-last">
            {children}
          </div>
        </div>

        <Toastr />
      </main>
    </>
  );
};

export default Layout;