import Head from "next/head";
import Navbar from "./Navbar";
import Toastr, { ToastrContext, ToastrContextType } from "./Toastr";
import { PropsWithChildren, useContext, useRef } from "react";
import type { ThemeContextType} from "./Theme";
import { ThemeContext } from "./Theme";
import { Portal } from '@headlessui/react'

const Layout: React.FC<PropsWithChildren> = ({children}) => {
  const { toasts } = useContext(ToastrContext) as ToastrContextType;
  const { theme } = useContext(ThemeContext) as ThemeContextType;
  
  const toastRef = useRef(null)

  return (
    <div className={theme}>
      <Head>
        <title>Shortify - ln</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-1 flex-col items-center min-h-screen isolate bg-white dark:bg-[#181818]">
        <Navbar />

        <div className="pt-[2rem] md:pt-[3rem] w-full pb-5 md:pb-8 flex flex-1">
          <div className="container mx-auto px-6 md:px-9 flex flex-1 justify-center order-first md:order-last">
            {children}
          </div>
        </div>

        <Portal>
          <div className={theme}>
            <Toastr />
          </div>
        </Portal>
      </main>
    </div>
  );
};

export default Layout;