import Head from "next/head";
import { PropsWithChildren } from "react";
import Sidebar from "./Sidebar";
import Toastr, { ToastrProvider } from "./Toastr";

const Layout: React.FC<PropsWithChildren> = ({children}) => {
  return (
    <>
      <ToastrProvider>
        <Head>
          <title>Shortify - ln</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className="w-100 flex flex-col items-center min-h-screen isolate">
          <Toastr />

          <h1 className="mt-5 text-5xl md:text-[5rem] leading-normal font-extrabold text-gray-700 mx-auto">
            Shortify - <span className="text-purple-300">ln</span>
          </h1>

          <div className="w-screen flex flex-1 flex-row">
            <Sidebar />

            <div className="px-9 flex flex-1 md:mr-80 justify-center">
              {children}
            </div>
          </div>
        </main>
      </ToastrProvider>
    </>
  );
};

export default Layout;